### ISSUE TITLE
Bump required libraries up

### ISSUE THREAD

**Issue by perimore** [ivgg-me/aioremootio#11]
Hi, 

Would it be possible to bump up and test the following libraries please as the older ones specified are breaking integrations with home assistant:

aiohttp==3.8.5
pycryptodome==3.17

Thanks,
Sean

**Comment by drsmarsden** [comment]
I have https://github.com/drsmarsden/aioremootio.git.  working with HA 2023.12.1

**Comment by ivgg-me** [comment]
I updated the requirements.
