### ISSUE TITLE
authentication timeout causes loop that cannot recover

### ISSUE THREAD

**Issue by sj7trunks** [ivgg-me/aioremootio#5]
Home assistant seems to get stuck in a loop when it fails to connect to the device. This loop goes on indefinitely and only can be recovered by restarting home-assistant. 

Last night Home Assistant was restarted at 12, first authentication timeout happened at 5:26 AM. This works fine in the homebridge installation so perhaps a bug that is unable to recover when the first timeout happens.

> 2022-05-18 08:40:43 ERROR (MainThread) [custom_components.remootio.aioremootio.remootioclient] An error has been occurred on the device. Type [ErrorType.AUTHENTICATION_TIMEOUT]
> 2022-05-18 08:41:19 ERROR (MainThread) [custom_components.remootio.aioremootio.remootioclient] An error has been occurred on the device. Type [ErrorType.AUTHENTICATION_TIMEOUT]
> 2022-05-18 08:41:58 ERROR (MainThread) [custom_components.remootio.aioremootio.remootioclient] An error has been occurred on the device. Type [ErrorType.AUTHENTICATION_TIMEOUT]
> 2022-05-18 08:42:35 ERROR (MainThread) [custom_components.remootio.aioremootio.remootioclient] An error has been occurred on the device. Type [ErrorType.AUTHENTICATION_TIMEOUT]
> 2022-05-18 08:43:35 ERROR (MainThread) [custom_components.remootio.aioremootio.remootioclient] An error has been occurred on the device. Type [ErrorType.AUTHENTICATION_TIMEOUT]
> 2022-05-18 08:44:12 ERROR (MainThread) [custom_components.remootio.aioremootio.remootioclient] An error has been occurred on the device. Type [ErrorType.AUTHENTICATION_TIMEOUT]
> 2022-05-18 08:44:49 ERROR (MainThread) [custom_components.remootio.aioremootio.remootioclient] An error has been occurred on the device. Type [ErrorType.AUTHENTICATION_TIMEOUT]
> 

Randomly throughout the night this problem popped up

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/aioremootio/remootioclient.py", line 328, in __open_connection
>     self.__ws = await self.__client_session.ws_connect(
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 776, in _ws_connect
>     resp = await self.request(
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
>     await resp.start(conn)
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
>     message, payload = await protocol.read()  # type: ignore[union-attr]
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
>     await self._waiter
> aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
>

**Comment by ivgg-me** [comment]
> Home assistant seems to get stuck in a loop when it fails to connect to the device. This loop goes on indefinitely and only can be recovered by restarting home-assistant.
> 
> Last night Home Assistant was restarted at 12, first authentication timeout happened at 5:26 AM. This works fine in the homebridge installation so perhaps a bug that is unable to recover when the first timeout happens.
> 
> > 2022-05-18 08:40:43 ERROR (MainThread) [custom_components.remootio.aioremootio.remootioclient] An error has been occurred on the device. Type [ErrorType.AUTHENTICATION_TIMEOUT]
> > 2022-05-18 08:41:19 ERROR (MainThread) [custom_components.remootio.aioremootio.remootioclient] An error has been occurred on the device. Type [ErrorType.AUTHENTICATION_TIMEOUT]
> > 2022-05-18 08:41:58 ERROR (MainThread) [custom_components.remootio.aioremootio.remootioclient] An error has been occurred on the device. Type [ErrorType.AUTHENTICATION_TIMEOUT]
> > 2022-05-18 08:42:35 ERROR (MainThread) [custom_components.remootio.aioremootio.remootioclient] An error has been occurred on the device. Type [ErrorType.AUTHENTICATION_TIMEOUT]
> > 2022-05-18 08:43:35 ERROR (MainThread) [custom_components.remootio.aioremootio.remootioclient] An error has been occurred on the device. Type [ErrorType.AUTHENTICATION_TIMEOUT]
> > 2022-05-18 08:44:12 ERROR (MainThread) [custom_components.remootio.aioremootio.remootioclient] An error has been occurred on the device. Type [ErrorType.AUTHENTICATION_TIMEOUT]
> > 2022-05-18 08:44:49 ERROR (MainThread) [custom_components.remootio.aioremootio.remootioclient] An error has been occurred on the device. Type [ErrorType.AUTHENTICATION_TIMEOUT]
> 
> Randomly throughout the night this problem popped up
> 
> > Traceback (most recent call last):
> > File "/usr/local/lib/python3.9/site-packages/aioremootio/remootioclient.py", line 328, in __open_connection
> > self.__ws = await self.__client_session.ws_connect(
> > File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 776, in _ws_connect
> > resp = await self.request(
> > File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
> > await resp.start(conn)
> > File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
> > message, payload = await protocol.read()  # type: ignore[union-attr]
> > File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
> > await self._waiter
> > aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer

Thank you for your report. I will see what I can do, but this error occures when the device sends an error frame to the client with the info that the authentication has been timed out.

By the way, I have experienced this phenomenon also in the official app lately. 

Which firmware version has your Remootio device currently and in what way are you using this library in Home Assistant?

**Comment by sj7trunks** [comment]
Here's a new error I received that caused remootio to stop fetching data.

```
2022-05-20 22:47:58 ERROR (MainThread) [custom_components.remootio.aioremootio.remootioclient] Failed to initialize this client.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aioremootio/remootioclient.py", line 328, in __open_connection
    self.__ws = await self.__client_session.ws_connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 776, in _ws_connect
    resp = await self.request(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aioremootio/remootioclient.py", line 282, in __initialize
    await self.__open_connection(handle_connection_error=False)
  File "/usr/local/lib/python3.9/site-packages/aioremootio/remootioclient.py", line 336, in __open_connection
    raise RemootioClientConnectionEstablishmentError(
aioremootio.errors.RemootioClientConnectionEstablishmentError: Unable to establish connection to the device. Host [192.168.250.227] SerialNumber [N/A] ApiVersion [N/A] State [State.UNKNOWN]
2022-05-20 22:47:58 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Remootio Device (Host: 192.168.250.227, S/N: *******************) for remootio
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aioremootio/remootioclient.py", line 328, in __open_connection
    self.__ws = await self.__client_session.ws_connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 776, in _ws_connect
    resp = await self.request(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aioremootio/remootioclient.py", line 282, in __initialize
    await self.__open_connection(handle_connection_error=False)
  File "/usr/local/lib/python3.9/site-packages/aioremootio/remootioclient.py", line 336, in __open_connection
    raise RemootioClientConnectionEstablishmentError(
aioremootio.errors.RemootioClientConnectionEstablishmentError: Unable to establish connection to the device. Host [192.168.250.227] SerialNumber [N/A] ApiVersion [N/A] State [State.UNKNOWN]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/remootio/__init__.py", line 38, in async_setup_entry
    remootio_client: RemootioClient = await create_client(
  File "/config/custom_components/remootio/utils.py", line 73, in create_client
    result = await RemootioClient(
  File "/usr/local/lib/python3.9/site-packages/async_class.py", line 133, in __await__
    yield from self.__ainit__(*self._args, **self._kwargs).__await__()
  File "/usr/local/lib/python3.9/site-packages/aioremootio/remootioclient.py", line 260, in __ainit__
    await self.__initialize()
  File "/usr/local/lib/python3.9/site-packages/aioremootio/remootioclient.py", line 296, in __initialize
    raise RemootioClientError(self, "Failed to initialize this client.") from ex
aioremootio.errors.RemootioClientError: Failed to initialize this client. Host [192.168.250.227] SerialNumber [N/A] ApiVersion [N/A] State [State.UNKNOWN]
2022-05-20 22:47:58 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
```
Screenshot of unavailable plus the restart at the end.
<img width="390" alt="Screen Shot 2022-05-21 at 9 51 06 AM" src="https://user-images.githubusercontent.com/22721065/169661463-09790cca-6db5-44d0-ab97-a46a434cc09c.png">

Thanks for the quick response. I've seen both the app and the API both be finicky and the way I've resolved this for now is restarting home-assistant on error conditions. I would think the best way to handle this is to have home-assistant not fail hard when it gets these requests. It's entirely possible for a connection to break due to the nature of WIFI. 

This happens frequently so I'm happy to help debugging to see if something fixes the issues:


```
2022-05-19 21:54:12 Restarting Home Assistant
2022-05-19 22:49:22 Restarting Home Assistant
2022-05-19 23:19:18 Restarting Home Assistant
2022-05-20 00:00:26 Restarting Home Assistant
2022-05-20 21:44:36 Restarting Home Assistant
2022-05-20 22:45:54 Restarting Home Assistant
```

Apologies on mentioning homebridge - I didn't mean to infer that it was using your code. Only that it recovered from the error. Here's the link to [remoootio for homebridge](https://github.com/ronniepettersson/homebridge-remootio) .

**Comment by ivgg-me** [comment]
To which version of the client do your comments refer? I have completely refactored the code of the client some time ago. It seems to me that the errors you found refer to an older version.

**Comment by sj7trunks** [comment]
not able to reproduce with latest version, closing
